
# Cosmetics
RED := "\e[1;31m"
YELLOW := "\e[1;33m"
NC := "\e[0m"
INFO := @bash -c 'printf $(YELLOW); echo "=> $$1"; printf $(NC)' MESSAGE
ERROR := @bash -c 'printf $(RED); echo "ERROR: $$1"; printf $(NC); exit 1' MESSAGE

# Functions
rwildcard = $(shell find $1 -name "$2")
VALGRIND := $(shell which valgrind 2>/dev/null)
VALGRIND_CMD := valgrind --leak-check=full --show-leak-kinds=all \
	--track-origins=yes  --error-exitcode=1 \
	--verbose $(1)
