name: Barzane CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build lib, test and main
      run: make buid
    - name: Run tests
      run: make build:lib build:test test
    - name: Check heap memory
      run: make build:lib build:test test && apt-get install -y valgrind && valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose bin/testbarzane
